---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: parth-sharma
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "parthdocker12/spe_mini_image"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Mini project parthdocker12/spe_mini_image